### PR TITLE
Support Debian 10

### LINKED ISSUE #1121: Support Debian 10
Sensu Go 5.11 supports Debian 10. Currently there are no Debian 10 packages for Puppet so that is the main road block.

I believe this is current Puppet issue: https://tickets.puppetlabs.com/browse/PA-2402

### PR DESCRIPTION
**Pull request by treydock**
# Pull Request Checklist

## Description

Add Debian 10 support

## Related Issue

Fixes #1121 

## Motivation and Context

Sensu Go added support for Debian 10.

### CODE REVIEW

**Comment by treydock** [comment]
This is WIP because right now the only Puppet repos for Debian 10 are nightlies.

**Comment by ghoneycutt** [comment]
Great work @treydock

**Comment by treydock** [comment]
Removed WIP as now am testing Debian 10 against just Puppet 6.

**Comment by ghoneycutt** [comment]
Travis failures are unrelated and due to a bug introduced in Puppet 6.8.0.

https://tickets.puppetlabs.com/browse/PUP-9975

**Pull request merged**
