### PR TITLE
Avoid running sensu enterprise service in opensource installation

### PR DESCRIPTION
**Pull request by devcfgc**
Not sure why this PR https://github.com/sensu/sensu-puppet/pull/409 was rolled-back in this commit https://github.com/sensu/sensu-puppet/commit/932324c44d06ecf2d2e039f70669ded4954ef5c2 but  as the first PR reported I'm getting:
```
Error: /Stage[main]/Sensu::Enterprise::Service/Service[sensu-enterprise]: Could not evaluate: Could not find init script or upstart conf file for 'sensu-enterprise'
Notice: /Stage[main]/Sensu::Enterprise::Dashboard/Anchor[sensu::enterprise::dashboard::begin]: Dependency Service[sensu-enterprise] has failures: true
Warning: /Stage[main]/Sensu::Enterprise::Dashboard/Anchor[sensu::enterprise::dashboard::begin]: Skipping because of failed dependencies
Notice: /Stage[main]/Sensu::Enterprise::Dashboard::Config/File[/etc/sensu/dashboard.json]: Dependency Service[sensu-enterprise] has failures: true
Warning: /Stage[main]/Sensu::Enterprise::Dashboard::Config/File[/etc/sensu/dashboard.json]: Skipping because of failed dependencies
Notice: /Stage[main]/Sensu::Enterprise::Dashboard::Config/Sensu_enterprise_dashboard_config[ubuntu1.vagrant.local]: Dependency Service[sensu-enterprise] has failures: true
Warning: /Stage[main]/Sensu::Enterprise::Dashboard::Config/Sensu_enterprise_dashboard_config[ubuntu1.vagrant.local]: Skipping because of failed dependencies
Notice: /Stage[main]/Sensu::Enterprise::Dashboard::Service/Service[sensu-enterprise-dashboard]: Dependency Service[sensu-enterprise] has failures: true
Warning: /Stage[main]/Sensu::Enterprise::Dashboard::Service/Service[sensu-enterprise-dashboard]: Skipping because of failed dependencies
Notice: /Stage[main]/Sensu::Enterprise::Dashboard/Anchor[sensu::enterprise::dashboard::end]: Dependency Service[sensu-enterprise] has failures: true
Warning: /Stage[main]/Sensu::Enterprise::Dashboard/Anchor[sensu::enterprise::dashboard::end]: Skipping because of failed dependencies
Notice: /Stage[main]/Sensu/Anchor[sensu::end]: Dependency Service[sensu-enterprise] has failures: true
Warning: /Stage[main]/Sensu/Anchor[sensu::end]: Skipping because of failed dependencies
```

### CODE REVIEW

**Comment by devcfgc** [comment]
I'm working on fixing the tests failed :grinning:

**Comment by devcfgc** [comment]
There were test failing before my PR:
```
Finished in 33.67 seconds (files took 1.19 seconds to load)
362 examples, 7 failures

Failed examples:

rspec ./spec/classes/sensu_enterprise_spec.rb:128 # sensu on Debian when enterprise => true should contain Apt::Source[sensu-enterprise] with release => "sensu-enterprise"
rspec ./spec/classes/sensu_package_spec.rb:93 # sensu package repos ubuntu with puppet-apt installed default should contain Apt::Source[sensu] with ensure => "present", location => "http://repositories.sensuapp.org/apt", release => "trusty", repos => "main", include => {"src"=>false}, key => {"id"=>"EE15CFF6AB6E4E290FDAB681A20F259AEB9C94BB", "source"=>"http://repositories.sensuapp.org/apt/pubkey.gpg"} and before => "Package[sensu]"
rspec ./spec/classes/sensu_package_spec.rb:116 # sensu package repos ubuntu with puppet-apt installed unstable repo should contain Apt::Source[sensu] with repos => "unstable"
rspec ./spec/classes/sensu_package_spec.rb:121 # sensu package repos ubuntu with puppet-apt installed override repo url should contain Apt::Source[sensu] with location => "http://repo.mydomain.com/apt"
rspec ./spec/classes/sensu_package_spec.rb:123 # sensu package repos ubuntu with puppet-apt installed override repo url should not contain Apt::Key[sensu] with key => {"id"=>"EE15CFF6AB6E4E290FDAB681A20F259AEB9C94BB", "source"=>"http://repo.mydomain.com/apt/pubkey.gpg"}
rspec ./spec/classes/sensu_package_spec.rb:131 # sensu package repos ubuntu with puppet-apt installed override key ID and key source should not contain Apt::Key[sensu] with key => {"id"=>"FFFFFFFF", "source"=>"http://repo.mydomain.com/apt/pubkey.gpg"}
rspec ./spec/classes/sensu_package_spec.rb:158 # sensu package repos debian repo release should contain Apt::Source[sensu] with ensure => "present", location => "http://repositories.sensuapp.org/apt", release => "jessie", repos => "main", include => {"src"=>false}, key => {"id"=>"EE15CFF6AB6E4E290FDAB681A20F259AEB9C94BB", "source"=>"http://repositories.sensuapp.org/apt/pubkey.gpg"} and before => "Package[sensu]"

```

**Comment by dzeleski** [comment]
409 was rolled back due to it breaking the ability to use manage_service = false for enterprise users. 

Your changes are inline with that I was thinking to fix https://github.com/sensu/sensu-puppet/issues/662

Let me know if you need assistance on this.

**Comment by devcfgc** [comment]
@dzeleski It'd be lovely to have the build of this repository fixed [travis-ci url](https://travis-ci.org/sensu/sensu-puppet)
There are some test failing related to `sensu package repos ubuntu`
Thank you for your help :+1:

**Comment by dzeleski** [comment]
@devcfgc I've reached out to Sensu and included @cwjohnston on this. It appears the apt module from puppet was updated a few weeks ago adding a new required fact which is causing the spec test to fail. We are still looking into it but I assume one of us will send a PR to your branch to resolve it.

**Comment by dzeleski** [comment]
@devcfgc do me a favor. https://github.com/devcfgc/sensu-puppet/blob/9913cf998fea3e18d9412cb83f0efb9677281d0e/spec/classes/sensu_enterprise_spec.rb#L121

Make that line look like this:
```
let(:facts) { { :osfamily => 'Debian', :lsbdistid => 'ubuntu', :lsbdistrelease => '14.04', :lsbdistcodename => 'trusty', :os => {'name' => 'Debian'}, }
```

Push that up and see if this entry goes away: https://travis-ci.org/sensu/sensu-puppet/jobs/242385983#L2169

If that works we can correct the others.

**Comment by devcfgc** [comment]
@dzeleski there wasn't any luck :'( , after adding this line:
`let(:facts) { { :osfamily => 'Debian', :lsbdistid => 'ubuntu', :lsbdistrelease => '14.04', :lsbdistcodename => 'trusty', :os => {'name' => 'debian'}, } }`
I'm still getting:
`rspec ./spec/classes/sensu_enterprise_spec.rb:128 # sensu on Debian when enterprise => true should contain Apt::Source[sensu-enterprise] with release => "sensu-enterprise"
`
Let me know if you need me to do some other test :+1:

**Comment by cwjohnston** [comment]
@devcfgc I have fixed the apt related failures in https://github.com/sensu/sensu-puppet/pull/663. Will you please rebase your branch on current master and see where that gets us?

**Comment by devcfgc** [comment]
nice!! good job, now all the test are green :+1: 
@cwjohnston @dzeleski Thank you guys for your help.

**Comment by dzeleski** [comment]
Yep no problem. Apologies on re introducing that issue. 

@cwjohnston let me know if we want to test this stuff on the enterprise side before merging I can pull it into our lab and test.

**Pull request merged**
