### PR TITLE
Additional bolt tasks

### PR DESCRIPTION
**Pull request by treydock**
Added task to list outdated bonsai assets. This is part of fixing #1147 

Add a few comments that didn't get pushed with #1153 .

### CODE REVIEW

**Comment by treydock** [comment]
This PR is additional bolt tasks and a commit that was missing from #1153

**Comment by ghoneycutt** [comment]
We should have a bolt tasks section of the readme that lists the tasks and explains what they do and how to use them, just like the basics for the classes.

**Comment by treydock** [comment]
Wouldn't that duplicate the puppet strings auto generated docs? The docs are generated when pushed to forge based on the JSON metadata. I just wasn't sure how much we wanted to duplicate automatic docs. Still think warrants more than Strings docs?

**Comment by treydock** [comment]
https://forge.puppet.com/sensu/sensu/tasks

I don't see tasks in the strings docs on github but when I generate the docs locally I see tasks getting put into REFERENCE.md and the docs directory. Maybe release for bolt tasks didn't receive automatic doc updates?

I'd prefer to rely on code to document things especially since metadata is a core part of bolt tasks. If there is something lacking from the auto docs that can't be added to the auto docs then I can update readme.

**Comment by ghoneycutt** [comment]
We don't want the docs in the README to just replicate puppet-strings generated docs. Listing what the tasks are with a sentence or two about it let's folks you read the README understand what is possible from a glance.

**Comment by treydock** [comment]
Added section to README

**Pull request merged**
