### PR TITLE
(GH-786) sensu::plugin does not work on windows without specifying install_path

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Working on issue https://github.com/sensu/sensu-puppet/issues/786.

Add Linux/Windows sensitive default values for sensu::plugin::install_path.
Adjust calls of sensu::plugin to not set install_path anymore.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
Will continue to work on ```tests/sensu-client-windows.pp``` once I understood how to use and modify the Vagrant test suite.

**Comment by ghoneycutt** [comment]
@Phil-Friderici if you put `Solves #123` then when this ticket closes it will automatically close the referenced ticket. 

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by ghoneycutt** [comment]
Solves #786

**Comment by ghoneycutt** [comment]
Released in v2.31.0

**Pull request merged**
