### PR TITLE
Hiera sensu client config

### PR DESCRIPTION
**Pull request by countryHick**
attempting to fix test cases for merging - refer to https://github.com/sensu/sensu-puppet/issues/366

### CODE REVIEW

**Comment by pdaugavietis** [comment]
bah - not working after all - need to play more (works for me locally - but not against test cases :(

**Comment by jlambert121** [comment]
What's the issue you're attacking with this PR?

**Comment by pdaugavietis** [comment]
#366 - merging all layers of hiera, instead of lowest one - works fine locally, but the tests seem to fail :(   and the one that passed looks OK - but doesn't appear to merge them.   so i'm trying again :)   apologies for the hacking...

**Comment by pdaugavietis** [comment]
this one is looking good now...  needed to combine the stdlib merge/union, with defaults and default hiera_array/hiera_hash values.   working for me as needed

**Comment by jlambert121** [comment]
I tend to override these settings from the default in my config, having them now be merged by default would be an issue for me personally.  What's the issue you're working to solve?  To go down this path I think it needs to be an option, not the default.

**Comment by pdaugavietis** [comment]
i'm not sure i follow your comment - how to override - just update the module after installed to call hiera_array/hiera_hash?

I'm having default subscriptions and/or client_custom data, based on certain facts, which are different layers of hierarchy (default, network, production/non, etc.) - and i want to merge all the layers of hiera into a single array/hash (as needed) to allow that type of config - i don't want to just override ALL the configs again on lowest level (hosts/fqdn in our case).

To avoid duplication, that's why im using hiera_hash/array wrapped in a merge/union as well.

**Comment by pdaugavietis** [comment]
I'll take pointers for how to make it more optional than default though...  and i think i just realized what you meant - you override (change) the subscriptions/client_custom (more?) on lower levels of the hierarchy, instead of just mashing them together...   fair point - this wouldn't allow for override, only merge...

dammit ;P

**Comment by countryHick** [comment]
okay - as discussed on IRC - i'll rework this a bit to have override/merge triggers, instead of by default merge behaviour.

**Comment by countryHick** [comment]
need add one more merger -- for plugins as well...

**Comment by jlambert121** [comment]
A couple of things on this when you're ready... please squish everything down to 1 commit and we need some tests around this as well.

**Comment by countryHick** [comment]
k - how to squish, and how to test :)

**Comment by jlambert121** [comment]
Quickly googling on squishing I found this: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request (look at squash)

Same on testing I found this: http://ask.puppetlabs.com/question/60/what-is-the-recommended-method-for-testing-modules-that-use-hiera/?answer=17865#post-id-17865

**Comment by mrolli** [comment]
Why is it necessary to introduce hiera calls from within the module. IMHO this is a very bad decision. Module's should not do hiera calls anymore. You can do the hiera call yourself outside the module and provide its result by using the respective parameter to sensu, i.e. in manifests/init.pp there's simply no need for using a hiera_call. The call to hiera_hash is client code and its result provded by $plugins.

**Comment by countryHick** [comment]
fair thought -- this is to provide merge options to override default hiera/puppet behaviour -- if this shouldn't sit in the module, you'd have to wrap a module/class around this one, to provide the override behaviour, which is the other way to go.

i'm open to discussion and direction - i certainly have the need to override base behaviour, but others could still use it too?

**Comment by jlambert121** [comment]
After @mrolli's comment I actually think that may be a better solution...

This could be as simple as doing the hiera functions in your profile:

```puppet
class { 'sensu':
  subscriptions => union ( hiera_array('sensu::subscriptions', []), $sensu::subscriptions )
  ....
}
```

**Comment by countryHick** [comment]
fair nuff

**Pull request closed without merging**
