### PR TITLE
plugins should be hash and use create_resources

### PR DESCRIPTION
**Pull request by r0b0tAnthony**
The current use of plugins param is an array for files only. This isn't necessarily a problem but the install_path is not dynamic so you can't use it on windows. In general, a better solution is for plugins to be like checks and be a hash. This allow multiple plugin types and allows the install_path to be overwritten on per plugin basis or using plugins_defaults.

### CODE REVIEW

**Comment by jaxxstorm** [comment]
This changes default behavior and therefore needs some tests adding, I can help if required

**Comment by ghoneycutt** [comment]
@Phil-Friderici could you please have a look. I think we should continue to support having a string or array using Puppet4's lambdas. For a hash, we could do the same or use create_resources(), as you see fit.

**Comment by Phil-Friderici** [comment]
Working on this in https://github.com/sensu/sensu-puppet/pull/703

**Comment by ghoneycutt** [comment]
Thanks everyone!

@Phil-Friderici rebased @r0b0tAnthony 's work in PR #703 which has been merged.

**Comment by ghoneycutt** [comment]
Released in v2.11.0

**Pull request closed without merging**
