### PR TITLE
Disable user creation on osfamily = windows by default

### PR DESCRIPTION
**Pull request by cdenneen**
This is to address #617

### CODE REVIEW

**Comment by cwjohnston** [comment]
I understand that the change here is motivated by factors described in https://github.com/sensu/sensu-puppet/issues/586#issuecomment-290190265. 

@jaxxstorm do you have any concerns about this from a SemVer perspective? I'm not sure if this change would require a major version bump, or what the plans are for the next release.

**Comment by jaxxstorm** [comment]
I've been trying to track major versions with sensu versions, I think we can probably get away with doing a minor bump here as long as we make it clear what's happened in the changelog.

**Comment by cwjohnston** [comment]
@dzeleski I take it from [your comment in #617](https://github.com/sensu/sensu-puppet/issues/617#issuecomment-289966990) that you're 👍  on this change? If so I think we can merge it.

**Comment by dzeleski** [comment]
@cwjohnston In my lab, running on about 30 systems. I try not to run things that are not in the release branch in prod. No issues thus far.

**Pull request merged**
