### PR TITLE
Change sensu_api_validator default test_url

### LINKED ISSUE #979: Ensure sensu_api_validator is not using deprecated API endpoints
## Description of problem

Upstream deprecated the `/info` API endpoint (https://github.com/sensu/sensu-go/pull/2066).  This endpoint is used by `sensu_api_validator` to ensure other sensuctl resources don't get added before sensu-backend is ready to accept requests.

I think the endpoint may have been removed completely.

```
[root@sensu-backend ~]# puppet apply test.pp
Notice: Compiled catalog for sensu-backend.example.com in environment production in 0.12 seconds
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
Notice: Unable to connect to sensu_api server (http://localhost:8080): [404] Not Found
Notice: Failed to connect to sensu_api within timeout window of 30 seconds; giving up.
Notice: /Stage[main]/Main/Sensu_check[test2]/ensure: created
Notice: Applied catalog in 30.31 seconds
[root@sensu-backend ~]# cat test.pp
sensu_api_validator { 'sensu': }
sensu_check { 'test2':
        command       => 'check-cpu.rb',
        subscriptions => ['demo'],
        handlers      => ['email'],
        interval      => 60,
      }
```

### PR DESCRIPTION
**Pull request by treydock**
# Pull Request Checklist

## Description

Upstream removed /info: https://github.com/sensu/sensu-go/pull/2066

The /health endpoint allows unauthenticated queries:

```
[root@sensu-backend ~]# curl http://localhost:8080/health
{"Alarms":null,"ClusterHealth":[{"MemberID":9882886658148554927,"Name":"default","Err":"","Healthy":true}]}
```

## Related Issue

Fixes #979  .

## Motivation and Context

Ensure `sensu_api_validator` will work with latest sensu-go.

## How Has This Been Tested?

```
[root@sensu-backend ~]# cat test.pp
sensu_api_validator { 'sensu': }
sensu_check { 'test2':
        command       => 'check-cpu.rb',
        subscriptions => ['demo'],
        handlers      => ['email'],
        interval      => 60,
      }
[root@sensu-backend ~]# puppet apply test.pp
Notice: Compiled catalog for sensu-backend.example.com in environment production in 0.12 seconds
Notice: Applied catalog in 0.12 seconds
```

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@treydock could you please rebase this and resubmit

**Comment by treydock** [comment]
Rebased.

**Comment by ghoneycutt** [comment]
@treydock Travis is unhappy, could you please have a look

**Comment by treydock** [comment]
Looks like upstream change broke check extra hash property by adding new key to check resource.  Looks like we need to filter out `output` key.  I'll open new PR

**Pull request merged**
