### PR TITLE
Revert "Flapjack support for puppet"

### PR DESCRIPTION
**Pull request by jlambert121**
Reverts sensu/sensu-puppet#284

I'm going to revert this for a few reasons:

This by default will install the flapjack extension for all users
The flapjack plugin is pulled directly from GH meaning installs are not idempotent (that file changes over time)
- which leads to we need a generic method for installing extensions as well as configuring them

### CODE REVIEW

**Comment by jessereynolds** [comment]
Awww, exciting...

**Comment by jlambert121** [comment]
This was added as generic extension support in #297

**Comment by jessereynolds** [comment]
@jlambert121 ah brilliant, thanks.

**Comment by poolski** [comment]
Beautiful!

**Pull request merged**
