### PR TITLE
Replace id properties with name and use metadata

### LINKED ISSUE #1012: Update sensu2 to replace id properties with name
Upstream is changing references to `id` with `name` and this will require some changes to several types.  Also appears like the `metadata` key will be used for `name` and `namespace` combinations and this will also require some logic changes for most types.

Upstream PR: https://github.com/sensu/sensu-go/pull/2308

### PR DESCRIPTION
**Pull request by treydock**
# Pull Request Checklist

## Description

Several properties that had `id` in name are now using `name`.  Also all resources that belong to a namespace are now using the `metadata` key to hold both `name` and `namespace` attributes.

## Related Issue

Fixes #1012.  Contains fixes for #1005 , #1006 and #1008.  This pull request contains the changes in #1010 because this is an extension of the changes in that pull request.

## Motivation and Context

Upstream made some massive changes to the data structures for JSON in/out of sensuctl.  These changes should get the sensu2 branch full updated to work with current code for sensu-go.

## How Has This Been Tested?

Unit tests only.  The acceptance tests will not work until new RPMs are released.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@portertech @cwjohnston  We need nightly releases of the beta software released so we can automatically test the changes that are happening with sensu-go.

**Comment by cwjohnston** [comment]
@ghoneycutt as I understand it, an effort to revamp packaging has lead us to turn off nightly builds for the time being. Many of us are advocating for the return of nightly builds, but at this time there's currently no specific timeline for bringing them back.

**Comment by treydock** [comment]
Added commit to resolve #1014 and one item in #901

**Comment by treydock** [comment]
Two new commits.  First adds descriptions to properties that were missing now that Sensu docs have all these new things documented.

Second commit adds `labels` and `annotations` to all types that didn't already have them and support the new resource metadata.

**Pull request merged**
