### PR TITLE
MacOS support except for API

### PR DESCRIPTION
**Pull request by csoleimani**
# Pull Request Checklist

adding macOS support

## Description
adding macOS support

## Related Issue

Fixes # .

## Motivation and Context
wanted to get this working for macs

## How Has This Been Tested?
got it working with a mac vagrant machine except for the API.

## General

- [ ] Update `README.md` with any necessary configuration snippets

- [ ] New parameters are documented

- [ ] New parameters have tests

- [ ] Tests pass - `bundle exec rake validate lint spec`

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Thanks for taking this on! Could you please add an entry to the Vagrantfile along with a provisioning script so that we can test that this work.

**Comment by csoleimani** [comment]
I used https://vagrantcloud.com/jhcook/boxes/osx-yosemite-10.10/versions/10.10.5/providers/virtualbox.box this vagrant box, but I didn't really use a provisioning script to set this up. I just used a test puppet master for my testing instead of doing masterless provisioning. I might need some help on getting the provisioning script working on MacOS, but I'll take a stab at it

**Comment by ghoneycutt** [comment]
Client support only is OK. Assigning Gary Larizza to help with this.

**Comment by csoleimani** [comment]
Thanks! I was able to get this bootstrap script working to install Puppet on the Mac, but I wasn't able to get the shared folder sync working to try applying a class

```
#!/bin/bash

cd /tmp && curl -O https://downloads.puppetlabs.com/mac/10.11/PC1/x86_64/puppet-agent-1.9.3-1.osx10.11.dmg
sudo hdiutil mount /tmp/puppet-agent-1.9.3-1.osx10.11.dmg
sudo installer -pkg /Volumes/puppet-agent-1.9.3-1.osx10.11/puppet-agent-1.9.3-1-installer.pkg -target /
```

**Comment by glarizza** [comment]
I have some time today to jump into this, so I'm gonna see how far I get this morning.  I'll leave comments/questions as I go if I need some help :)

**Comment by csoleimani** [comment]
Cool, let me know if I can help :)

**Comment by glarizza** [comment]
To be honest I've been wrestling with macOS vagrant box issues all morning (both pulling down from Vagrant cloud as well as getting them to boot up).  I'd like to target this against a macOS Sierra box just do the to speed that Apple updates macOS - have you tested against Sierra yet?

I also added a couple of things to try and get provisioning scripts setup for both Puppet and the modules.  Hashicorp has a great repo for Puppet provisioning scripts, and I added the macOS one, along with the Vagrantfile stanza, in this commit --> https://github.com/glarizza/sensu-puppet/commit/71c864b7cc342a69dba14a2165fe45786d1c5a7d

**Comment by csoleimani** [comment]
I have tested this on Sierra using a test puppet master and it worked. I'm having issues getting it to work with this module's Vagrantfile because of this message:

```
Vagrant is not able to mount VirtualBox shared folders on BSD-based
guests. BSD-based guests do not support the VirtualBox filesystem at
this time.
```

Can you think of any workaround?

**Comment by csoleimani** [comment]
I finally got it working in a Vagrant, but it's kind of patched together because I couldn't get git installed on the VM or use the shared folders, but here is what my Vagrantfile looks like:
```
Vagrant.configure("2") do |config|
  config.vm.box = "jhcook/macos-sierra"
  config.vm.hostname = 'test-mac.test.com'
  config.vm.network  :private_network, ip: "192.168.56.19"
  config.vm.provision :shell, :path => "tests/mac_puppet.sh"
  config.vm.provision :shell, :inline => "puppet apply /etc/puppetlabs/code/environments/production/modules/sensu/tests/sensu-client-mac.pp"
end
```
I saw a few warnings, but this is what the puppet run looked like:

```
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
==> default:    (in /etc/puppetlabs/puppet/hiera.yaml)
==> default: Warning: Unknown variable: '::sensu::service_name'. at /etc/puppetlabs/code/environments/production/modules/sensu/manifests/init.pp:453:31
==> default: Notice: Compiled catalog for test-mac.test.com in environment production in 1.11 seconds
==> default: Notice: /Stage[main]/Sensu::Package/Remote_file[/tmp/sensu-installer.dmg]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/Package[sensu]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/default/sensu]/content: content changed '{md5}26728b32eacbda7a6442310c0b2bd191' to '{md5}2a7cc6ee5f843601712fb8160bd60baa'
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/default/sensu]/mode: mode changed '0644' to '0444'
==> default: Notice: /Stage[main]/Sensu::Package/Group[root]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/User[_sensu]/home: defined 'home' as '/opt/sensu'
==> default: Notice: /Stage[main]/Sensu::Package/User[_sensu]/comment: defined 'comment' as 'Sensu Monitoring Framework'
==> default: Notice: /Stage[main]/Sensu::Package/User[_sensu]/shell: shell changed '/usr/bin/false' to '/bin/false'
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/conf.d]/group: group changed '_sensu' to 'root'
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/conf.d]/mode: mode changed '0755' to '0555'
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/conf.d/handlers]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/conf.d/checks]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/conf.d/filters]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/conf.d/extensions]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/conf.d/mutators]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/conf.d/contacts]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/handlers]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/extensions]/group: group changed '_sensu' to 'root'
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/extensions]/mode: mode changed '0755' to '0555'
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/extensions/handlers]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/mutators]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/plugins]/group: group changed '_sensu' to 'root'
==> default: Notice: /Stage[main]/Sensu::Package/File[/etc/sensu/plugins]/mode: mode changed '0755' to '0555'
==> default: Notice: /Stage[main]/Sensu::Transport/File[/etc/sensu/conf.d/transport.json]/ensure: defined content as '{md5}2d99a43075d786eb1ef71c18e19e69eb'
==> default: Notice: /Stage[main]/Sensu::Rabbitmq::Config/File[/etc/sensu/conf.d/rabbitmq.json]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Rabbitmq::Config/Sensu_rabbitmq_config[test-mac.test.com]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Api/File[/etc/sensu/conf.d/api.json]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Api/Sensu_api_config[test-mac.test.com]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Redis::Config/File[/etc/sensu/conf.d/redis.json]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Redis::Config/Sensu_redis_config[test-mac.test.com]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Client/File[/etc/sensu/conf.d/client.json]/ensure: created
==> default: Notice: /Stage[main]/Sensu::Client/Sensu_client_config[test-mac.test.com]/ensure: created
==> default: Warning: The /System/Library/LaunchDaemons/com.apple.jetsamproperties.Mac.plist plist does not contain a 'label' key; Puppet is skipping it
==> default: Notice: /Stage[main]/Sensu::Client/Service[org.sensuapp.sensu-client]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: /Stage[main]/Sensu/Sensu::Filter[offhours]/File[/etc/sensu/conf.d/filters/offhours.json]/ensure: created
==> default: Notice: /Stage[main]/Sensu/Sensu::Filter[offhours]/Sensu_filter[offhours]/ensure: created
==> default: Notice: Applied catalog in 18.13 seconds
```

**Comment by csoleimani** [comment]
I am going to close this and re-open it from a non master branch in my repo

**Comment by csoleimani** [comment]
I got this working. Please see this pull request:

https://github.com/sensu/sensu-puppet/pull/826

**Pull request closed without merging**
