### PR TITLE
fixed 385, add owner group sensu:sensu to plugins dir and plugins files

### LINKED ISSUE #385: plugins directory permissions inconsistent
The plugins directory permissions are inconsistent.
Type: file - owned by sensu
Type: directory - owned by root/puppet
Type: URL - owned by sensu (but files underneath root/puppet)
Type: package - Sounds like there are permissions issues here as well.

### PR DESCRIPTION
**Pull request by hurrycaine**
ensure sensu:senu is owner of plugins_dir for type directory and plugin files for type url fixed #385

### CODE REVIEW

**Comment by hurrycaine** [comment]
Not sure what is going on with all the failures ...its failing before it gets to the tests and nothing like that was changed. Do not think we got a valid test.

The errors start very early
line 129
FAILED: tar -Pzxf /home/travis/.casher/fetch.tgz /home/travis/build/sensu/sensu-puppet/vendor/bundle
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

It fails right before the tests are ran with ...

"spec/defines/sensu_handler_spec.rb" "spec/defines/sensu_plugin_spec.rb" "spec/defines/sensu_subscription_spec.rb" "spec/unit/puppet_x_sensu_totype_spec.rb" "spec/unit/sensu_redis_config_spec.rb"
*** Mocha deprecation warning: `require 'mocha/standalone'` has been deprecated. Please use `require 'mocha/api' instead.
/home/travis/build/sensu/sensu-puppet/vendor/bundle/ruby/2.0.0/gems/rspec-core-2.0.0/lib/rspec/core/mocking/with_mocha.rb:2:in `require': cannot load such file -- mocha/object (LoadError)

**Comment by hurrycaine** [comment]
The previous good Travice CI build user rspec 2.99.0
this build used 2.0.0

I was able to test this locally by removing my Gemfile.lock and adding rspec version 2.0.0 before rspec-puppet. 

gem 'rspec', "2.0.0",              :require => false

I could not get rspec-puppet to pull down rspec 2.0.0 any other way, no idea why it happened here. 
Maybe it was an aberration? I am not sure how to rerun the travis build. I could add rspec ~> 2.99.0 to enforce it...

**Comment by hurrycaine** [comment]
Closing and reopening to trigger a new build

**Comment by jlambert121** [comment]
That's annoying, I should revisit my PR where I updated some gems and travis config - might fix this as well.

**Comment by jlambert121** [comment]
Can you rebase and see if that fixes the tests?

**Comment by hurrycaine** [comment]
Done. I did have to fix a trailing comma for ruby 1.8.7 rspec after all!

**Comment by jlambert121** [comment]
Thanks!

**Pull request merged**
