### PR TITLE
Added hooks support #836

### LINKED ISSUE #836: Implement hooks
Currently it appears this module does not support hooks. As this was released in 1.1 I assume others will start wanting to use it at some point. We are trying to start testing them now which is how we ran into it. Basically just wanted to get this open to track the feature, I will attempt to get a PR going if I have some free time later this week.

### PR DESCRIPTION
**Pull request by alvagante**
# Pull Request Checklist

Introduces support for hooks

## Description
Commit addes the hooks parameter to the sensu::check define

## Related Issue
Fixes #836 

## How Has This Been Tested?
Spec tested.
Integration test on PSICK setup.

## General

- [x] Update `README.md` with any necessary configuration snippets

- [x] New parameters are documented

- [x] New parameters have tests

- [x] Tests pass - `bundle exec rake validate lint spec`

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Can you please add a test for us to verify this works in vagrant.

**Comment by ghoneycutt** [comment]
@dzeleski Could you please test that this works for you before we release it. Thanks!!!

**Comment by dzeleski** [comment]
Yep will do, working on that now. Might have to get back to you first thing in the morning though as I have to leave around 6pm EST tonight.

**Comment by dzeleski** [comment]
Inputs and outputs below, let me know if you need anything else tested. @ghoneycutt 

Input:
```
sensu::check{ 'cl-pup-healthcheck-puppet_pemaster':
    command     => '/opt/sensu/embedded/bin/ruby /opt/sensu/embedded/bin/check-puppet-healthcheck.rb',
    handlers    => 'linux_handler',
    interval    => 300,
    subscribers => 'puppet_pemaster',
    standalone  => false,
    occurrences => 1,
    notify      => Service['sensu-enterprise'],
    hooks       => {
      critical => {
        command => 'test command',
        },
    },
  }
```

Output:
```
{
    "checks": {
        "cl-pup-healthcheck-puppet_pemaster": {
            "command": "/opt/sensu/embedded/bin/ruby /opt/sensu/embedded/bin/check-puppet-healthcheck.rb",
            "handlers": [
                "linux_handler"
            ],
            "hooks": {
                "critical": {
                    "command": "test command"
                }
            },
            "interval": 300,
            "occurrences": 1,
            "standalone": false,
            "subscribers": [
                "puppet_pemaster"
            ]
        }
    }
}
```

**Comment by alvagante** [comment]
@ghoneycutt Added vagrant test manifests and check on the name of the hooks (I didn't realise that only some specific values are accepted) with relevant spec test.
Rebased and ready to merge (if travis won't surprise me).

**Comment by ghoneycutt** [comment]
Thank you everyone for your help getting this implemented!!

Released in v2.39.0

**Pull request merged**
