### PR TITLE
Allow gem_install_options on sensu_gem plugins

### PR DESCRIPTION
**Pull request by statyk**
# Pull Request Checklist

## Related Issue

Fixes # .

## General

- [ ] Update `README.md` with any necessary configuration snippets

- [x] New parameters are documented

- [x] New parameters have tests

- [x] Tests pass - `bundle exec rake validate lint spec`

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Looks good. @treydock could you please test our matrix in vagrant and confirm.

**Comment by treydock** [comment]
@ghoneycutt majority of tests pass.  Failures unrelated to this module.

```
sensu-server                pass
sensu-server-cluster        pass
sensu-server-puppet5        pass
sensu-server-enterprise     pass
el7-client                  pass
el6-client                  pass
ubuntu1604-client           pass
ubuntu1404-client           pass
amazon201703-client         failed - vagrant
win2012r2-client            pass
win2012r2-client-chocolatey failed - unable to install from chocolatey
debian9-client              failed - vagrant
debian8-client              pass
debian7-client              pass
macos-client                failed - vagrant
```

**Comment by ghoneycutt** [comment]
@treydock could you please open issues for why the tests failed with Vagrant. I'd like to be sure they are not somehow related before merging this.

**Comment by ghoneycutt** [comment]
Released in v2.53.0

**Comment by cdenneen** [comment]
**2.53.0** still has same issue above exactly.
Was this only tested with linux? Maybe gem.bat can't take a `--source` parameter? or the quoting is what's throwing it off? @treydock @ghoneycutt  any ideas?

**Comment by ghoneycutt** [comment]
Thanks @cdenneen for reporting this! Opened Issue #908 to track this.

**Pull request merged**
