### PR TITLE
Add support to rotate windows logs

### PR DESCRIPTION
**Pull request by dzeleski**
The windows agent was not rotating logs correctly. I added support for that here, some changes to how logging is done was altered to add this support. Im open to discussion if we think we need to adjust it briefly but there are now separate log files for each type of output.

https://github.com/sensu/sensu-puppet/issues/618

https://github.com/sensu/sensu/issues/1617

### CODE REVIEW

**Comment by cdenneen** [comment]
@dzeleski sent you PR

**Comment by dzeleski** [comment]
@cdenneen Cool, ty. Were you able to test those changes out? I wont be able to get to testing it until Monday.

**Comment by cdenneen** [comment]
@dzeleski I didn't write specific tests but it's passing travis tests that are there.

**Comment by dzeleski** [comment]
@cdenneen sorry I mean did you run the code in puppet on some nodes? I assume it works based on looking at it. Ill be able to pull the code down Monday and test in my lab regardless.

**Comment by cwjohnston** [comment]
I think this looks good. 

For posterity I'll point out that this log rotation implementation relies on the behavior of the winsw service wrapper. Instead of specifying `--log FILE` as a flag for the Sensu daemon, the rendered XML will start the service daemon with stdout and stderr logging captured by winsw instead of being written directly by the daemon as is done on Linux platforms.

**Pull request merged**
