### PR TITLE
Working on PR501

### PR DESCRIPTION
**Pull request by Phil-Friderici**
- Keep backward compatibility
- Updating docs
- Adding tests for https://github.com/sensu/sensu-puppet/pull/501

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@Phil-Friderici Looks good. Could you please update the README to show that hashes are also allowed. BTW, when referring to an issue, use `(GH-###)` in the commit where ### is the issue number (GH is for GitHub).

You can see previous commits here - https://github.com/sensu/sensu-puppet/commits/master

**Comment by Phil-Friderici** [comment]
@ghoneycutt README is updated. I didn't found a matching issue for this new feature. Did I miss it ?

**Comment by Phil-Friderici** [comment]
Maybe we shouldn't propagate the usage of strings for plugins in the docs explicitly?
I guess on the long run arrays and hashes should keep supported only.

**Comment by ghoneycutt** [comment]
Released in v2.11.0

**Pull request merged**
