### PR TITLE
Allow undef handlers and subscribers

### PR DESCRIPTION
**Pull request by thejandroman**
This commit fixes the error message: `undefined method `sort' for
nil:NilClass`. This error message can be seen when either the handlers
or subscribers parameters are passed in as  `undef` in the check.pp
manifest.

The PRs that looks like they introduced this behavior are:
https://github.com/sensu/sensu-puppet/pull/285
https://github.com/sensu/sensu-puppet/pull/303

### CODE REVIEW

**Comment by thejandroman** [comment]
Rebased.

**Comment by jaxxstorm** [comment]
Can you add a test for this?

**Comment by thejandroman** [comment]
I sure can!

**Comment by thejandroman** [comment]
I've added preliminary tests for subscribers and handlers but I'm having a hard time testing the exact scenario that causes this issue; namely passing in `undef` to the custom type. Any help or ideas on how to better test this would be appreciated.

**Comment by thejandroman** [comment]
Also these tests weren't written with ruby 1.8.7 in mind... Looks like those are failing. Will revise.

**Comment by jaxxstorm** [comment]
Awesome!

**Pull request merged**
