### PR TITLE
add sensu_default_handler type

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
I've fallen down on doing TDD this afternoon and haven't written any unit tests [yet] but wanted to get this out for comments before investing additional effort on it.

**Comment by jhoblitt** [comment]
Specifically, I'd appreciate some feedback in terms of approach -- I've only been a sensu user since last Friday.  This type is different then the existing family of types in that multiple resources are managing a single file.

**Comment by jlambert121** [comment]
I've been using a default handler by just naming it 'default' - something like:

```puppet
  sensu::handler { 'default':
    type      => 'set',
    handlers  => ['mailer', 'hipchat', 'logstash'],
  }
```

Could your needs be met by just doing this as well?

**Comment by jlambert121** [comment]
@jhoblitt thoughts on my comment?

**Comment by jhoblitt** [comment]
@jlambert121 My apologies -- currently traveling.  I suspect that will work for me. Is it considered safe to combine multiple separate files that each declare a default handler?  I haven't had a chance to dig into the code to confirm how "sets" are merged.

**Comment by jlambert121** [comment]
@jhoblitt I'm going to close this for now, let me know if naming the handler default doesn't work for you and we can revist.

**Comment by chuckwired** [comment]
Hi @jlambert121 , we've come across this issue and although we could create a `default` subscriber with a handler called `default`, Sensu will by default look for a handler named `default_handler.json` with a `default` definition for any checks without an explicit subscriber.

We've tried using `default_handler` and `default` for the name using this module with no luck, the file name and the handler definition must be as described above.

The use case is we want a default handler that acts as a "cleanup" if you like for any checks that don't have an explicit subscriber, ensuring the system is cleaner/tighter.

Is there any chance we could re-open this?

**Comment by lauraglasu** [comment]
:+1: @chuckwired

**Comment by jlambert121** [comment]
I have created a default handler in 3 environments now without the need for this PR.  Below is almost exactly what I'm running now using the "newly added" sensu::handlers hiera lookup.

```
sensu::handlers:
  default:
    type: set
    handlers:
      - mailer
      - slack
  mailer:
    type: pipe
    command: /etc/sensu/handlers/handler-mailer.rb
    config:
      mail_from: sensu@somewhere.com
      mail_to: alerts@somewhere.com
      smtp_address: localhost
  slack:
    type: pipe
    command: /etc/sensu/handlers/handler-slack.rb
    config:
      webhook_url: my_secret_url
      channel: '#alerts'
      bot_name: sensu
```

**Comment by chuckwired** [comment]
@jlambert121 what versions of the stack are you using for your environments if you don't mind me asking? I'm hoping that will shed light on this problem as I've tried exactly as you've described above but that creates a file called `default.json` which our sensu server was unable to pick up.

For us we exhibit this issue running the following:
```
OS: Centos 7.2.1511
Puppet: 3.8.7
sensu-puppet: 2.0.0 with modifications from @jhoblitt
sensu-api: 0.25.5
Ruby: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```

**Pull request closed without merging**
