### PR TITLE
Update of apt::source to support new version of puppetlabs-apt

### PR DESCRIPTION
**Pull request by zdenekjanda**
This is needed for supporting new puppetlabs-apt module versions.

### CODE REVIEW

**Comment by jamtur01** [comment]
Looks like some tests failed.

Is it backwards compatible?

**Comment by zdenekjanda** [comment]
Backward compatibility needs to be improved, but do we need it ? Here similar situation - https://github.com/jenkinsci/puppet-jenkins/pull/301. New apt will break most of modules around, similar discussions all around.

**Comment by jlambert121** [comment]
I think this is a dupe of #348.  We've merged some stuff that ups our puppet dependencies, maybe we merge one of these and figure out what else we need/want for a major version bump.

**Comment by zdenekjanda** [comment]
I am in favor of #348 then, closing this PR.

**Pull request closed without merging**
