### PR TITLE
sensu-puppet-add heartbeat feature

### PR DESCRIPTION
**Pull request by derkgort**
add support for setting the rabbitmq heartbeat value #559

### CODE REVIEW

**Comment by jaxxstorm** [comment]
@derkgort there's a bunch of unrelated changes which have slipped in here which have caused the tests to fail. Can you please reassess?

**Comment by derkgort** [comment]
Yeah sorry. That was not my best work...
I'll retry later this week..

**Comment by derkgort** [comment]
I fixed my error from before.
In the other pull request (#559) I was asked to make the rabbitmq_heartbeat default undef.
Should I still do this?

**Comment by jaxxstorm** [comment]
@derkgort yes, but you'll also need to update the tests so they pass. Thanks for cleaning this up.

**Comment by derkgort** [comment]
The travis checks pass. Do I need to check something else?

**Comment by jaxxstorm** [comment]
Nope, this looks good, i will merge it after my Christmas break :)

**Comment by dzeleski** [comment]
@derkgort I think im running into an issue with this change, previously the following config would work:
```
         version: '0.27.0-1'
         install_repo: true
         purge: true
         rabbitmq_cluster:
          - host: 'plxlb-sensu01.domain.lan'
            port: 5672
            vhost: '/sensu'
            user: 'sensu'
            password: 'secret'
            heartbeat: 30
            prefetch: 50
          - host: 'plxlb-sensu02.domain.lan'
            port: 5672
            vhost: '/sensu'
            user: 'sensu'
            password: 'secret'
            heartbeat: 30
            prefetch: 50
          - host: 'plxlb-sensu03.domain.lan'
            port: 5672
            vhost: '/sensu'
            user: 'sensu'
            password: 'secret'
            heartbeat: 30
            prefetch: 50
```

Im now getting the following error on both rhel and windows:
```
Could not evaluate: no implicit conversion of String into Integer
Source:/Stage[main]/Sensu::Rabbitmq::Config/Sensu_rabbitmq_config[tv99988mwl02.ntstdev.lan]
File:/etc/puppetlabs/code/environments/lab/modules/sensu/manifests/rabbitmq/config.pp
Line:125
```

Im thinking something between the normal rabbitmq and rabbitmq_cluster config is getting messed up? If you look here: https://github.com/derkgort/sensu-puppet/blob/5ff634aba010e6e161d765380d204e5b09cf9767/manifests/rabbitmq/config.pp#L111-L123 It looks like there is an override to deal with the regular rabbitmq config options when a cluster is specified.

**Comment by dzeleski** [comment]
@derkgort @jaxxstorm Please see the following changes:

https://github.com/dzeleski/sensu-puppet/commit/e223f96afcc32b7f9290d4a2673462d54d822b01

I basically copied what was working for prefetch.

**Comment by derkgort** [comment]
@dzeleski 
This looks like a better version. I contains more checking, which is good.
I don't know about the default change. There was some discussion about with my change.

I'd suggest to send a PR. That's what I did to get it changed.

**Pull request merged**
