### PR TITLE
Allow for undefined command param on ensure => absent

### PR DESCRIPTION
**Pull request by kali-hernandez**
Before this change, declaring a sensu::check to be absent with no command would fail:

```
  sensu::check {
    'check_system_raid':
      ensure => 'absent';
  }
```

The above would cause:

```
Error: Could not retrieve catalog from remote server:
Error 400 on SERVER:
Evaluation Error:
Error while evaluating a Resource Statement, Sensu::Check[check_system_raid]:
expects a value for parameter 'command' at [..] on node [...]
```

This commit allows for undefined `command` parameter which would be validated only if ensure is present (default), raising a specific error if command is missing.

### CODE REVIEW

**Comment by jaxxstorm** [comment]
This is breaking the tests I'm afraid, can you have another look?

**Comment by kali-brandwatch** [comment]
I have the feeling this failure on the tests have nothing to do with the commit, maybe they're failing because I rebased the PR on your master, which is failing tests as well?

Travis' output claims:
```
Failed examples:

rspec ./spec/classes/sensu_enterprise_spec.rb:131 # sensu on Debian when enterprise => true should contain Apt::Source[sensu-enterprise] with release => "sensu-enterprise"

rspec ./spec/classes/sensu_package_spec.rb:75 # sensu package repos ubuntu with puppet-apt installed default should contain Apt::Source[sensu] with ensure => "present", location => "http://repositories.sensuapp.org/apt", release => "sensu", repos => "main", include => {"src"=>false}, key => {"id"=>"EE15CFF6AB6E4E290FDAB681A20F259AEB9C94BB", "source"=>"http://repositories.sensuapp.org/apt/pubkey.gpg"} and before => "Package[sensu]"

rspec ./spec/classes/sensu_package_spec.rb:98 # sensu package repos ubuntu with puppet-apt installed unstable repo should contain Apt::Source[sensu] with repos => "unstable"

rspec ./spec/classes/sensu_package_spec.rb:103 # sensu package repos ubuntu with puppet-apt installed override repo url should contain Apt::Source[sensu] with location => "http://repo.mydomain.com/apt"

rspec ./spec/classes/sensu_package_spec.rb:105 # sensu package repos ubuntu with puppet-apt installed override repo url should not contain Apt::Key[sensu] with key => {"id"=>"EE15CFF6AB6E4E290FDAB681A20F259AEB9C94BB", "source"=>"http://repo.mydomain.com/apt/pubkey.gpg"}

rspec ./spec/classes/sensu_package_spec.rb:113 # sensu package repos ubuntu with puppet-apt installed override key ID and key source should not contain Apt::Key[sensu] with key => {"id"=>"FFFFFFFF", "source"=>"http://repo.mydomain.com/apt/pubkey.gpg"}

/home/travis/.rvm/rubies/ruby-2.0.0-p598/bin/ruby -I/home/travis/build/sensu/sensu-puppet/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.2/lib:/home/travis/build/sensu/sensu-puppet/vendor/bundle/ruby/2.0.0/gems/rspec-support-3.5.0/lib /home/travis/build/sensu/sensu-puppet/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.2/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration,types\}/\*\*/\*_spec.rb --color failed
```

Which AFAIK are not related to this commit.

Should i rebase the PR onto some other branch/tag?

**Comment by kali-brandwatch** [comment]
A closer investigation on the Travis logs finds:
```
     Puppet::Error:

       Unable to determine lsbdistid, please install lsb-release first at /home/travis/build/sensu/sensu-puppet/spec/fixtures/modules/apt/manifests/params.pp:134 on node testing-worker-linux-docker-74a5288c-3421-linux-9.prod.travis-ci.org
```
I'm not familiar with the tests, but I really doubt this has anything to do with the content of this PR? If you could give me a hint on how to fix this error I could make any changes.

**Comment by kali-brandwatch** [comment]
Seems indeed related to https://github.com/sensu/sensu-puppet/issues/511

**Comment by kali-hernandez** [comment]
Force pushed new commit to ammend author to my personal account, no changes in the code.

**Comment by kali-brandwatch** [comment]
@jaxxstorm: any news on this?

**Comment by jaxxstorm** [comment]
opened #533 to try and get the tests passing again, will look over the weekend. sorry for the delay

**Comment by kali-hernandez** [comment]
Cool, thanks for keeping an eye on that

**Comment by kali-brandwatch** [comment]
Seems like the tests are fixed? How can I re-submit the travis checks?

**Comment by jaxxstorm** [comment]
@kali-hernandez simply merge the master branch into your fork and repush with the new fixes commits

**Comment by kali-brandwatch** [comment]
Cool, so tests are passing now

**Comment by Phil-Friderici** [comment]
working on this in PR https://github.com/sensu/sensu-puppet/pull/745

**Comment by ghoneycutt** [comment]
Thanks everyone! Released in v2.25.0

**Comment by Phil-Friderici** [comment]
this PR could be closed now

**Pull request closed without merging**
