### PR TITLE
Add support for slack channel configuration / check.

### PR DESCRIPTION
**Pull request by oszknagy**
Hi there,

I've added support to the sensu_check provider to support custom channel configuration pre check   
It enables one or more channel to be specified per check.

Please see the multi channel handler script for the reference.
https://github.com/sensu-plugins/sensu-plugins-slack/blob/master/bin/handler-slack-multichannel.rb

Regards,
Oszkar

### CODE REVIEW

**Comment by jaxxstorm** [comment]
Personally, I'd rather see this not merged. The options that are defined already are directly available inside sensu and are params in the sensu documentation, and anything else can be covered by sensu_custom.

Merging this opens up things like hipchat channels, and other things being added.

**Comment by jbehrends** [comment]
I'd have to agree.  I have Hipchat integrated without any special code in the sensu module.  I don't see why we would need to deviate and add slack specific code to this module.

**Comment by jlambert121** [comment]
Thank you for your time on this, I think this can be achieved using the $config parameter already and opens the door to a nearly limitless set of properties someone may want to define.

**Comment by oszknagy** [comment]
That's right that it is possible to implement with the custom parameter. 
But it looks like the custom parameter has a bug.  
```      custom:
       'slack':
         channels: 
           - '#avc'```
If you pass the above config via hiera it will changes the file on every puppet run .

**Pull request closed without merging**
