### PR TITLE
init.pp: get rid of the ugly hack to compute $check_notify

### PR DESCRIPTION
**Pull request by amosshapira**
Proposed cleanup of the "ugly hack".

### CODE REVIEW

**Comment by amosshapira** [comment]
It appears that the failures in build 692 (https://travis-ci.org/sensu/sensu-puppet/builds/72221455) are due to Mocha interface change with Ruby 1.9, nothing to do with my code change.

**Comment by jlambert121** [comment]
Can you rebase and see if that fixes the tests?

**Comment by amosshapira** [comment]
I rebased on latest master and updated the tests to always expect an array in `notify`.
This gets all tests green except the Puppet 3.3 tests.
There is still a problem with `notify` being empty in all Puppet 3.3.0 tests.
I suspect that the issue is old version of `puppet-stdlib` including a broken version of `delete_undef_values()`, but I don't see the exact version used in the test in, for instance, https://travis-ci.org/sensu/sensu-puppet/jobs/73102376 and am not familiar enough with the tools to reproduce it locally on the Vagrant box.
Could you give me some more direction on how can I execute the tests inside the Vagrant box?
Thanks.

**Comment by jlambert121** [comment]
I was just trying to duplicate this on my machine without any luck.  I installed puppet 3.3.2 for my tests using bundler:

```shell
PUPPET_GEM_VERSION=3.3.2 bundle update
```

and all of the tests ran fine.

```shell
➜  sensu-puppet git:(master) bundle exec rake test
---> syntax:manifests
---> syntax:templates
---> syntax:hiera:yaml
Cloning into 'spec/fixtures/modules/apt'...
remote: Counting objects: 106, done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 106 (delta 9), reused 58 (delta 7), pack-reused 0
Receiving objects: 100% (106/106), 66.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (9/9), done.
Checking connectivity... done.
Cloning into 'spec/fixtures/modules/stdlib'...
remote: Counting objects: 409, done.
remote: Compressing objects: 100% (273/273), done.
remote: Total 409 (delta 149), reused 265 (delta 122), pack-reused 0
Receiving objects: 100% (409/409), 168.76 KiB | 0 bytes/s, done.
Resolving deltas: 100% (149/149), done.
Checking connectivity... done.
Cloning into 'spec/fixtures/modules/wget'...
remote: Counting objects: 38, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 38 (delta 5), reused 22 (delta 4), pack-reused 0
Receiving objects: 100% (38/38), 18.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (5/5), done.
Checking connectivity... done.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Users/jlambert/Documents/evenup/git/puppet/sensu-puppet/.bundle/vendor/gems/rspec-core-3.3.2/lib:/Users/jlambert/Documents/evenup/git/puppet/sensu-puppet/.bundle/vendor/gems/rspec-support-3.3.0/lib /Users/jlambert/Documents/evenup/git/puppet/sensu-puppet/.bundle/vendor/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color
.......................................................................................................................................................................

Finished in 19.7 seconds (files took 1.77 seconds to load)
167 examples, 0 failures

➜  sensu-puppet git:(master) bundle exec puppet --version
3.3.2
```

I'm not quite sure what's different with travis right now.

**Comment by amosshapira** [comment]
Thanks for testing. Travis mentions 3.3.0 specifically. Also I'd like to verify the stdlib version used in that 3.3.0 environment.

**Comment by jlambert121** [comment]
The .travis file specifies ~> 3.3.0 so it should be the latest patch in the 3.3 series (which is 3.3.2).  The version of stdlib it is using is master from git (in the .fixtures file it specifies the modules)

**Comment by amosshapira** [comment]
Using the commands you quoted above, I managed to replicated the problem inside the sensu-server vagrant box:
```
/usr/bin/ruby1.9.1 -I/var/lib/gems/1.9.1/gems/rspec-core-3.3.2/lib:/var/lib/gems/1.9.1/gems/rspec-support-3.3.0/lib /var/lib/gems/1.9.1/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color
...........................................................................................FFF.........................................................................

Failures:

  1) sensu::check notifications only client should contain Sensu_check[mycheck] with notify => ["Class[Sensu::Client::Service]"]
     Failure/Error: it { should contain_sensu_check('mycheck').with(:notify => ['Class[Sensu::Client::Service]'] ) }
       expected that the catalogue would contain Sensu_check[mycheck] with notify set to ["Class[Sensu::Client::Service]"] but it is set to []
     # ./spec/defines/sensu_check_spec.rb:104:in `block (4 levels) in <top (required)>'

  2) sensu::check notifications only server should contain Sensu_check[mycheck] with notify => ["Class[Sensu::Server::Service]"]
     Failure/Error: it { should contain_sensu_check('mycheck').with(:notify => ['Class[Sensu::Server::Service]'] ) }
       expected that the catalogue would contain Sensu_check[mycheck] with notify set to ["Class[Sensu::Server::Service]"] but it is set to []
     # ./spec/defines/sensu_check_spec.rb:109:in `block (4 levels) in <top (required)>'

  3) sensu::check notifications only api should contain Sensu_check[mycheck] with notify => ["Class[Sensu::Api::Service]"]
     Failure/Error: it { should contain_sensu_check('mycheck').with(:notify => ['Class[Sensu::Api::Service]'] ) }
       expected that the catalogue would contain Sensu_check[mycheck] with notify set to ["Class[Sensu::Api::Service]"] but it is set to []
     # ./spec/defines/sensu_check_spec.rb:114:in `block (4 levels) in <top (required)>'

Finished in 1 minute 41.95 seconds (files took 1.74 seconds to load)
167 examples, 3 failures

Failed examples:

rspec ./spec/defines/sensu_check_spec.rb:104 # sensu::check notifications only client should contain Sensu_check[mycheck] with notify => ["Class[Sensu::Client::Service]"]
rspec ./spec/defines/sensu_check_spec.rb:109 # sensu::check notifications only server should contain Sensu_check[mycheck] with notify => ["Class[Sensu::Server::Service]"]
rspec ./spec/defines/sensu_check_spec.rb:114 # sensu::check notifications only api should contain Sensu_check[mycheck] with notify => ["Class[Sensu::Api::Service]"]

/usr/bin/ruby1.9.1 -I/var/lib/gems/1.9.1/gems/rspec-core-3.3.2/lib:/var/lib/gems/1.9.1/gems/rspec-support-3.3.0/lib /var/lib/gems/1.9.1/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color failed
```
I have to step away from keyboard for a few days now. I'll get back to this later. Thanks for the tip.

**Comment by ghoneycutt** [comment]
Thanks @amosshapira @jlambert121 

I've fixed this up and rebased in PR #725

**Comment by ghoneycutt** [comment]
Functionality released in v2.19.1

**Pull request closed without merging**
