### PR TITLE
Add platform specific user and group for transport

### LINKED ISSUE #838: Transport class does not use platform specific user and group
The following occurs on windows:
`change from 'NT AUTHORITY\SYSTEM' to 'sensu' failed: Could not find group sensu`

`/etc/puppetlabs/code/environments/lab/modules/sensu/manifests/transport.pp:21`

Looks like the transport class is not using the platform specific var?

https://github.com/sensu/sensu-puppet/blob/master/manifests/transport.pp#L23

Needs to look something like this:
```
  file { "${sensu::conf_dir}/transport.json":
    ensure  => $ensure,
    owner   => $::sensu::user,
    group   => $::sensu::group,
    mode    => '0440',
    content => inline_template('<%= JSON.pretty_generate(@transport_type_hash) %>'),
    notify  => $::sensu::check_notify,
}
```

### PR DESCRIPTION
**Pull request by dzeleski**
# Pull Request Checklist

Fixes transport class for windows

## Description
Add sensu user and group vars to file enforcement in the transport class

## Related Issue

Fixes #838

## How Has This Been Tested?
Our lab, on RHEL 6 and 7 as well as Windows Server 2012R2, using Puppet 2017.3.1

## General

- [x] Update `README.md` with any necessary configuration snippets

- [x] New parameters are documented

- [x] New parameters have tests

- [x] Tests pass - `bundle exec rake validate lint spec`

### CODE REVIEW

**Comment by dzeleski** [comment]
After testing we had the following changes:
```
owner changed 'BUILTIN\Administrators' to 'NT AUTHORITY\SYSTEM'
group changed 'NT AUTHORITY\SYSTEM' to 'BUILTIN\Administrators'
```

This appears to be an updated user and group due to using an older verison of the module. I see no issues with these defaults. Let me know if anything else needs to be adjusted @ghoneycutt

**Comment by ghoneycutt** [comment]
@dzeleski Looks good! Thank you!

@alvagante Could you please verify this with our Vagrant windows system.

**Comment by dzeleski** [comment]
Updated PR with testing platform.

**Comment by dzeleski** [comment]
Sorry to be a pain in the ass, any idea on when this might get cut for a release? @ghoneycutt @alvagante 

We are a 50/50 shop RHEL/Win, without this we cant role this module out as it breaks our puppet runs for windows systems.

**Comment by ghoneycutt** [comment]
This was addressed in #841

**Comment by ghoneycutt** [comment]
Released in v2.40.0

**Comment by dzeleski** [comment]
Oh even better, TY!

**Comment by dzeleski** [comment]
Oh even better, TY!

**Comment by dzeleski** [comment]
Oh even better, TY!

**Pull request closed without merging**
