### PR TITLE
Added the log_dir variable to the init.pp and sensu.erb

### PR DESCRIPTION
**Pull request by HawtDogFlvrWtr**
Created a log_dir variable so that users can specify a custom log directory. This is important for users who want to put all application data in a specific app folder

### CODE REVIEW

**Comment by jaxxstorm** [comment]
Can you add some tests please

**Comment by ghoneycutt** [comment]
@Phil-Friderici could you please add the tests.

**Comment by Phil-Friderici** [comment]
✔️

**Comment by Phil-Friderici** [comment]
Working on this in https://github.com/sensu/sensu-puppet/pull/718

**Comment by ghoneycutt** [comment]
Functionality added in PR #718 

Thanks everyone!

**Comment by ghoneycutt** [comment]
Released in v2.15.0

**Pull request closed without merging**
