### PR TITLE
added cluster

### PR DESCRIPTION
**Pull request by whermann**
everything was updated
rebase to master tests ok

### CODE REVIEW

**Comment by jaxxstorm** [comment]
@whermann I think this needs some tests, I can help if required.

**Comment by jacobmw** [comment]
Would really like to see this commit get merged.  Seems like just needing to fix a conflict?  Need any help?

**Comment by jaxxstorm** [comment]
@jacobmw we need some test coverage here as well, I can't merge this as it stands because it could be completely broken :)

**Comment by jacobmw** [comment]
ah, ok, I'll take a look and see if I can't write some tests.

**Comment by cwjohnston** [comment]
@whermann @jaxxstorm  @jacobmw I have local changes to rebase this branch on current master and add some spec test coverage. Shall I open a new PR?

**Comment by jaxxstorm** [comment]
Deprecated in favour of #581

**Pull request closed without merging**
