### PR TITLE
Redaction support

### PR DESCRIPTION
**Pull request by jaxxstorm**
This PR adds support for password redaction which is part of the sensu-core and has been since the early days.

I've also added a README to make use of it, as this isn't well documented.

I've set the value to undef for the time being but I think it could be debated that we should set "password" as the default value.

Any thoughts or feedback is very welcome.

### CODE REVIEW

**Comment by jaxxstorm** [comment]
ping @jamtur01 or @jlambert121 ?

**Comment by jlambert121** [comment]
I've never used redact because I couldn't find good documentation on it. :)  It does seem like `password` would be a valid default, but I'm a bit torn since it does change existing functionality.

**Comment by jaxxstorm** [comment]
I'd like to get this merged as we rely on the mainline sensu module for this. We can add defaults later.

ping @jlambert121

**Comment by jaxxstorm** [comment]
ping again @jamtur01 or @jlambert121

**Pull request merged**
