### PR TITLE
Update cluster config tests and usage examples to match sensu-go docs

### PR DESCRIPTION
**Pull request by treydock**
# Pull Request Checklist

## Description

Update test and usage examples for sensu cluster to match upstream docs.

## Motivation and Context

Make sensu cluster usage match upstream docs: https://docs.sensu.io/sensu-go/5.0/guides/clustering/#sensu-backend-configuration

## How Has This Been Tested?

beaker

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Waiting to confirm with Vagrant before merging.

**Comment by ghoneycutt** [comment]
@treydock `sensu-backend-peer1` and `sensu-backend-peer2` do not connect and create a cluster.

```
    sensu-backend-peer1: Notice: Unable to connect to sensu_api server (http://127.0.0.1:8080): Failed to open TCP connection to 127.0.0.1:8080 (Connection refused - connect(2) for "127.0.0.1" port 8080)
    sensu-backend-peer1: Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
```

```
    sensu-backend-peer2: Notice: Unable to connect to sensu_api server (http://127.0.0.1:8080): Failed to open TCP connection to 127.0.0.1:8080 (Connection refused - connect(2) for "127.0.0.1" port 8080)
    sensu-backend-peer2: Notice: Failed to connect to sensu_api; sleeping 2 seconds before retry
```

```
[root@sensu-backend ~]# sensuctl cluster member-list
         ID           Name           Peer URLs              Client URLs
 ────────────────── ───────── ─────────────────────── ───────────────────────
  8927110dc66458af   default   http://127.0.0.1:2380   http://localhost:2379
```

**Comment by treydock** [comment]
What commands did you run?  Because of how setting up a cluster works you have to run Puppet twice so starting with no VMs already existing you have to do `up` then `provision` to force Puppet to run twice.  The two nodes won't work until both have `sensu-backend` running so first run's `sensuctl configure` will fail.

Steps I took to test this locally are ones in README:

```
vagrant up sensu-backend-peer1 sensu-backend-peer2
vagrant provision sensu-backend-peer1 sensu-backend-peer2
```

**Comment by ghoneycutt** [comment]
Re-ran and it seems the cluster is not coming together properly and leaving `sensu-backend` out.

```
[root@sensu-backend ~]# sensuctl cluster member-list
         ID           Name           Peer URLs              Client URLs
 ────────────────── ───────── ─────────────────────── ───────────────────────
  8927110dc66458af   default   http://127.0.0.1:2380   http://localhost:2379
```

```
[root@sensu-backend-peer1 ~]# sensuctl cluster member-list
         ID            Name             Peer URLs                  Client URLs
 ────────────────── ────────── ─────────────────────────── ───────────────────────────
  ba325b4612cd097e   backend2   http://192.168.52.22:2380   http://192.168.52.22:2379
  ecb0ee48edceae18   backend1   http://192.168.52.21:2380   http://192.168.52.21:2379
```

```
[root@sensu-backend-peer2 ~]# sensuctl cluster member-list
         ID            Name             Peer URLs                  Client URLs
 ────────────────── ────────── ─────────────────────────── ───────────────────────────
  ba325b4612cd097e   backend2   http://192.168.52.22:2380   http://192.168.52.22:2379
  ecb0ee48edceae18   backend1   http://192.168.52.21:2380   http://192.168.52.21:2379
```

**Comment by treydock** [comment]
The `sensu-backend` isn't supposed to be included, only `backend1` and `backend2`.  The `sensu-backend` is only intended to be single-host backend.  What your seeing is expected.

**Pull request merged**
