### PR TITLE
added subdue to sensu_handler type to handle properly subdue option

### PR DESCRIPTION
**Pull request by bovy89**

### CODE REVIEW

**Comment by bovy89** [comment]
It appears that the failures in build 697 (https://travis-ci.org/sensu/sensu-puppet/builds/72286997) are due to Mocha, nothing to do with my code change.

**Comment by jlambert121** [comment]
Could you rebase and squash into a single commit and see if that fixes the tests?

**Comment by bovy89** [comment]
Done

**Comment by jlambert121** [comment]
Tests are much happier now, thanks!  Could you squash into a single commit and I'll merge it?

**Comment by bovy89** [comment]
Done

**Comment by jlambert121** [comment]
Thanks!

**Pull request merged**
