### PR TITLE
Adding auto_resolve param to sensu::check

### PR DESCRIPTION
**Pull request by sbilo**
## Related Issue
See https://github.com/sensu/sensu-puppet/issues/857

### CODE REVIEW

**Comment by alvagante** [comment]
@sbilo Would you add relevant spec tests here: https://github.com/sensu/sensu-puppet/blob/master/spec/defines/sensu_check_spec.rb ? Let me know if you need help for them.

**Comment by alvagante** [comment]
@ghoneycutt  I can add the missing spec tests here, if @sbilo has no time

**Comment by ghoneycutt** [comment]
@alvagante could you please add the spec tests and squash the commits.

**Comment by alvagante** [comment]
@sbilo @ghoneycutt Added tests in #872, this can be closed, the #872, with squashed commits is ready for merge.

**Pull request closed without merging**
