### PR TITLE
Updating APT source to use new apt module version

### PR DESCRIPTION
**Pull request by nicolas-fernandez-olx**
New version of Puppet APT module was released the PR will fix this issue:
``` 
Puppet (err): Invalid parameter include_src on Apt::Source[sensu] at /etc/puppet/modules/sensu/manifests/repo/apt.pp:35
```

### CODE REVIEW

**Comment by jamtur01** [comment]
Looks like you need to fix the tests. Thanks!

**Comment by nicolas-fernandez-olx** [comment]
@jamtur01 Fixed :)

**Comment by jamtur01** [comment]
LGTM - @jlambert121?

**Comment by jamtur01** [comment]
Looks like it might need a rebase too?

**Comment by jlambert121** [comment]
Should the minimum version of the apt module needed be updated if there was a parameter change?  Typically the top version isn't pinned to a bug fix version - I'm wondering if that needs to be updated as well.

**Comment by teran-mckinney** [comment]
@jlambert121 I think this was updated in the commit, it shows the requirement in metadata.json

@nicolas-fernandez-olx can you rebase this? I also could use this fix.

**Comment by bleuchtang** [comment]
I rebased @nicolas-fernandez-olx changes here: https://github.com/bleuchtang/sensu-puppet/tree/apt
I also add 'include apt' before apt::source call (otherwise, an error appeared for me).

**Comment by jamtur01** [comment]
@nicolas-fernandez-olx - can you rebase please and consider @bleuchtang's comment? Thanks!

**Comment by jlambert121** [comment]
@bleuchtang this PR looks like it might be abandoned - would you like to resurrect yours?  We're going to do a major version bump with the next release and it would be a good time to include this.

**Comment by bleuchtang** [comment]
Rebased from master and tests fixed here:  #361

**Comment by jamtur01** [comment]
Merged #361

**Pull request closed without merging**
