### PR TITLE
sensu-enterprise (if in manifest) also needs a notify for config changes

### PR DESCRIPTION
**Pull request by dtweet**

### CODE REVIEW

**Comment by jaxxstorm** [comment]
This looks good, can you rebase so the tests pass?

**Comment by cwjohnston** [comment]
@dtweet can you please rebase? I think this is a needed improvement 👍

**Comment by cwjohnston** [comment]
Thanks @dtweet! @jaxxstorm I think this is ready for review again.

**Comment by ghoneycutt** [comment]
Thanks everyone!

This is a duplicate of #495 and will be resolved in PR #720

**Comment by ghoneycutt** [comment]
Released in v2.19.1

**Pull request closed without merging**
