### PR TITLE
Sensu2 namespaces and extended_attributes changes

### LINKED ISSUE #1008: Remove or update extended_attributes for sensu2 types
Upstream replaced extended attributes with labels.  This will impact `sensu_check` and `sensu_entity` at the very least.

Upstream change: https://github.com/sensu/sensu-go/pull/2283

### PR DESCRIPTION
**Pull request by treydock**
# Pull Request Checklist

## Description

Replace `organization` and `environment` properties with `namespace`.
Replace `sensu_organization` and `sensu_environment` types with `sensu_namespace`.
Remove `metadata` property from `sensu_asset`
Add `labels` and `annotations` properties to `sensu_check`, `sensu_asset` and `sensu_entity`.
Only autorequire this module's `sensu_api_validator` for all types.
Improve strings docs

## Related Issue

Fixes #1008, #1006, and #1005 

## Motivation and Context

Upstream sensu-go has made some changes that require updates to the Puppet code.

## How Has This Been Tested?

Only tested with unit tests.  Unable to test with acceptance tests until new beta RPMs are released.

### CODE REVIEW

**Comment by treydock** [comment]
Tests will fail until upstream releases new RPMs.

**Comment by ghoneycutt** [comment]
@cwjohnston Restoring nightly releases would allow us to test this.

**Comment by treydock** [comment]
@ghoneycutt Want to close this in favor of #1013?  That pull request contains commits from this pull request plus other changes that have been merged upstream that are related.

**Comment by ghoneycutt** [comment]
OK.

**Pull request closed without merging**
