### PR TITLE
add support for setting the rabbitmq heartbeat value

### PR DESCRIPTION
**Pull request by derkgort**
This adds the heartbeat setting for rabbitmq, see #428

### CODE REVIEW

**Comment by jaxxstorm** [comment]
Can you default this to undef? A lot of setups won't have this configured, and I don't think we should change it by default.

**Comment by jbehrends** [comment]
I think having a default value of 30 is ok.  

This is a setting that appears in the [official Sensu documentation](https://sensuapp.org/docs/latest/reference/rabbitmq.html#sensu-rabbitmq-configuration-examples) as a default configuration.  Recently we went through a number of alert keepalive storms in our environment that this setting would have addressed.  As a result I've butt-patched my puppet code with this PR and verified it's working as expected.   

Adding this setting to most installs should have no net effect other than adding a few tcp packets every 30 seconds or so from each client during a internal AMQP heartbeat check.

+1 for this PR as is.

**Comment by derkgort** [comment]
Should I change it to undef?
I've moved the changed to a separate branch and updated to the current master branch.

https://github.com/derkgort/sensu-puppet/tree/feature/heartbeat

**Comment by jeffmccune** [comment]
Closing this pull-request via #596 and #623 

After reviewing this pull request, the desired functionality has been merged and released via #596 and #623.

**Pull request closed without merging**
