### PR TITLE
Dsc

### LINKED ISSUE #819: Running Sensu on Windows as a specific account
I have a need to run Sensu on Windows with a different account to the default LocalService/LocalSystem that it uses by default. This would require registering the service with some different Powershell that looks something like this:
```ps1
$securePassword = convertto-securestring -String "password" -AsPlainText -Force  
$credentialsObject = new-object -typename System.Management.Automation.PSCredential -argumentlist "username", $securePassword
New-Service -Name sensu-client -Credential $credentialsObject -BinaryPathName c:\\opt\\sensu\\bin\\sensu-client.exe -DisplayName 'Sensu Client' -StartupType Automatic
```
This doesn't strike me as something very idempotent if one were to change the account details after the service has already been registered.

Would it make sense to instead use one of the `dsc_service` or `dsc_xservice` types from the DSC module which should a) hide the scary Powershell and b) hopefully be a bit more idempotent w.r.t. the account credentials?

### PR DESCRIPTION
**Pull request by ghoneycutt**
# Pull Request Checklist

## Related Issue

Fixes #819 
Replaces #823 

## General

- [ ] Update `README.md` with any necessary configuration snippets

- [ ] New parameters are documented

- [ ] New parameters have tests

- [ ] Tests pass - `bundle exec rake validate lint spec`

### CODE REVIEW

**Comment by ghoneycutt** [comment]
still getting 

```
win2012r2-client: Warning: /Stage[main]/Sensu::Client/Service[sensu-client]: Skipping because of failed dependencies
win2012r2-client: Error: Could not find a suitable provider for dsc_service
```

**Comment by ghoneycutt** [comment]
@bodgit Any ideas on the error above?

**Comment by bodgit** [comment]
I'm not in any way a Windows expert, but is it possibly related to the version of Powershell installed?

**Comment by treydock** [comment]
Need Powershell 5 which comes from Windows Management Framework 5.0+, https://www.microsoft.com/en-us/download/details.aspx?id=54616.

A direct download is here: https://download.microsoft.com/download/6/F/5/6F5FF66C-6775-42B0-86C4-47D41F2DA187/Win8.1AndW2K12R2-KB3191564-x64.msu

Different errors once I install Powershell 5 through above link:

```
    win2012r2-client: Notice: Scope(Class[Sensu::Package]): Managing a local windows user is not implemented on windows
    win2012r2-client: Notice: Compiled catalog for win2012r2-client in environment production in 3.91 seconds
    win2012r2-client: Info: Applying configuration version '1529447643'
    win2012r2-client: Notice: /Stage[main]/Sensu::Package/Package[sensu]/ensure: created
    win2012r2-client: Info: Class[Sensu::Package]: Scheduling refresh of Service[sensu-client]
    win2012r2-client: Info: Computing checksum on file C:/opt/sensu/bin/sensu-client.xml
    win2012r2-client: Info: FileBucket got a duplicate file {md5}5dd4feefb65905221641722d60335bc1
    win2012r2-client: Info: /Stage[main]/Sensu::Client/File[C:/opt/sensu/bin/sensu-client.xml]: Filebucketed C:/opt/sensu/bin/sensu-client.xml to puppet with sum 5dd4feefb65905221641722d60335bc1
    win2012r2-client: Notice: /Stage[main]/Sensu::Client/File[C:/opt/sensu/bin/sensu-client.xml]/content: content changed '{md5}5dd4feefb65905221641722d60335bc1' to '{md5}67dcc6c38ffcf0b5c887891c185f5856'
    win2012r2-client: Notice: /Stage[main]/Sensu::Client/Service[sensu-client]: Dependency Dsc_service[sensu-client] has failures: true
    win2012r2-client: Info: /Stage[main]/Sensu::Client/Service[sensu-client]: Unscheduling all events on Service[sensu-client]
    win2012r2-client: Info: Class[Sensu::Client]: Unscheduling all events on Class[Sensu::Client]
    win2012r2-client: Info: Class[Sensu]: Unscheduling all events on Class[Sensu]
    win2012r2-client: Info: Stage[main]: Unscheduling all events on Stage[main]
    win2012r2-client: Error: PowerShell DSC resource MSFT_ServiceResource  failed to execute Set-TargetResource functionality with error message: The service 'sensu-client' to create already exists with path 'c:\opt\sensu\bin\sensu-client.exe'
    win2012r2-client: Error: /Stage[main]/Sensu::Client/Dsc_service[sensu-client]/ensure: change from absent to present failed: PowerShell DSC resource MSFT_ServiceResource  failed to execute Set-TargetResource functionality with error message: The service 'sensu-client' to create already exists with path 'c:\opt\sensu\bin\sensu-client.exe'
    win2012r2-client: Warning: /Stage[main]/Sensu::Client/Service[sensu-client]: Skipping because of failed dependencies
    win2012r2-client: Notice: Applied catalog in 152.05 seconds
==> win2012r2-client: Running provisioner: shell...
    win2012r2-client: Running: inline PowerShell script
    win2012r2-client: 0.29.0
```

**Comment by treydock** [comment]
I destroyed my local windows vagrant box and ran vagrant tests from scratch and this change is successful as long as WMF 5.1 is installed during provision.  I think this change would be problematic for sites that have already used this module with the previous Exec.  I'm going to try and verify that going from old behavior to this new behavior is the cause of errors in my previous comment.

**Comment by ghoneycutt** [comment]
Great insight! We don't want to replace this bit of functionality if the upgrade path is not going to work out for people.

**Comment by treydock** [comment]
Opened #917 that fixes Vagrant tests.  I couldn't reproduce the dsc_service errors.  I checked out master, ran `vagrant up win2012r2-client` then checked out branch with #917 and ran Puppet on the previous Vagrant box with no errors once provisioning scripts and box reloaded.

**Comment by ghoneycutt** [comment]
Thanks for the contributions! This PR has been extended in https://github.com/sensu/sensu-puppet/pull/917

**Pull request closed without merging**
